import turtle
t = turtle.Turtle()
c = turtle.Turtle()
t.circle(20)
t.hideturtle()
c.penup()
c.goto(70, 0)
c.pendown()
c.circle(20)
c.hideturtle()
face = turtle.Turtle()
face.penup()
face.goto(35,-100)
face.pendown()
face.circle(100)
nose = turtle.Turtle()
nose.penup()
nose.goto(35,-10)
nose.pendown()
nose.right(90)
nose.forward(40)
nose.hideturtle()
mouth = turtle.Turtle()
mouth.penup()
mouth.goto(0,-70)
mouth.pendown()
count = 0
while(count < 30):
    mouth.forward(5)
    mouth.left(1)
    count = count + 1
turtle.done()
